// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherApi.Data;

namespace WeatherApi.Migrations
{
    [DbContext(typeof(WeatherContext))]
    [Migration("20210201211849_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("WeatherApi.Models.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2021, 2, 2, 13, 18, 48, 714, DateTimeKind.Local).AddTicks(8988),
                            Summary = "Mild",
                            TemperatureC = 45
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2021, 2, 3, 13, 18, 48, 718, DateTimeKind.Local).AddTicks(3955),
                            Summary = "Hot",
                            TemperatureC = 34
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2021, 2, 4, 13, 18, 48, 718, DateTimeKind.Local).AddTicks(3980),
                            Summary = "Balmy",
                            TemperatureC = 13
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2021, 2, 5, 13, 18, 48, 718, DateTimeKind.Local).AddTicks(3985),
                            Summary = "Scorching",
                            TemperatureC = 12
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2021, 2, 6, 13, 18, 48, 718, DateTimeKind.Local).AddTicks(3987),
                            Summary = "Freezing",
                            TemperatureC = -6
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2021, 2, 7, 13, 18, 48, 718, DateTimeKind.Local).AddTicks(3991),
                            Summary = "Scorching",
                            TemperatureC = 34
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2021, 2, 8, 13, 18, 48, 718, DateTimeKind.Local).AddTicks(3997),
                            Summary = "Bracing",
                            TemperatureC = -18
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2021, 2, 9, 13, 18, 48, 718, DateTimeKind.Local).AddTicks(4000),
                            Summary = "Warm",
                            TemperatureC = 26
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2021, 2, 10, 13, 18, 48, 718, DateTimeKind.Local).AddTicks(4003),
                            Summary = "Balmy",
                            TemperatureC = 43
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2021, 2, 11, 13, 18, 48, 718, DateTimeKind.Local).AddTicks(4006),
                            Summary = "Hot",
                            TemperatureC = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
